# Generated by Django 2.1.15 on 2020-05-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_auto_20200516_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('work_description', models.CharField(max_length=500)),
                ('receiver_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='company.Company')),
                ('receiver_employe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='company.Employee')),
                ('sender_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='company.Company')),
                ('sender_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='company.Employee')),
            ],
        ),
    ]
