# Generated by Django 2.1.15 on 2020-05-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
